### ISSUE TITLE
Get automatic publishing working

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmet-qa-dashboard#20]
To get the app to automatically deploy to Posit Connect when code changes, @jeremylweiss will need to do the following:

- [x] Clone this repo
- [x] Run `renv::restore()` to install dependencies (if this doesn't work, @Aariq can help out)
- [x] Run the shiny app
- [x] Publish to Posit Connect the usual way
- [x] Get an API token from viz.datascience.arizona.edu and add to GitHub secrets as `CONNECT_APIKEY`
- [x] Edit `APP_NAME` to match the name it's published as https://github.com/uace-azmet/azmet-qa-dashboard/blob/f785a8d8afdd8c66e1437f16629a1696351b00cb/.github/workflows/deploy-to-connect.yaml#L18
- [x] Push to GitHub and check that the Action runs without error

**Comment by jeremylweiss** [comment]
Cloned to local machine. `renv::restore()` gives error

`Error: Error installing package 'units':
=================================

* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.8-2
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether clang++ -arch arm64 -std=gnu++17 accepts -g... yes
checking for clang++ -arch arm64 -std=gnu++17 option to enable C++11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for _Bool... no
checking for stdbool.h that conforms to C99... yes
checking for error_at_line... no
checking for gcc... clang -arch arm64
checking whether the compiler supports GNU C... yes
checking whether clang -arch arm64 accepts -g... yes
checking for clang -arch arm64 option to enable C11 features... none needed
checking for XML_ParserCreate in -lexpat... yes
checking for udunits2.h... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/private/var/folders/s5/bdtr8dws52l6864ps5d_fybs4ndqb1/T/RtmpfObaE5/R.INSTALL12da734b89cd6/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/Users/jlweiss/Library/CloudStorage/OneDrive-UniversityofArizona/Documents/azmet/data/new-system/azmet-qa-dashboard/renv/staging/1/units’
install of package 'units' failed [error code 1]`

**Comment by Aariq** [comment]
Yeah, I figured it wouldn't go perfectly.  This error is because some system dependencies (not R packages) are missing.  You need to install `udunits` in order to install the `units` R package.  On a mac, you can do that with `brew install udunits` in the terminal.  You might have to install [homebrew](https://docs.brew.sh/Installation) first.

**Comment by jeremylweiss** [comment]
Thanks for direction. For reference, and in addition to the Homebrew install, there was a hurdle with fortran compiling and the `Matrix` package that I got over with https://github.com/coatless-mac/macrtools

Second step done, onward!

**Comment by jeremylweiss** [comment]
Shiny app URL: https://viz.datascience.arizona.edu/azmet/azmet-qaqc-dashboard/

**Comment by jeremylweiss** [comment]
@Aariq The `deploy-to-connect.yaml` file opens as blank and doesn't allow changes to be saved, stating no such file or directory. Plus, there are several commits in waiting (below pic). Think I should push commits, which are on main branch, then try to tackle the .yaml file issue?

<img width="658" alt="Screen Shot 2023-08-09 at 12 05 19 PM" src="https://github.com/uace-azmet/azmet-qa-dashboard/assets/17934972/22e86dd0-c9fd-4b36-8faa-7fc01d9f4b3b">

**Comment by Aariq** [comment]
hmm, something doesn't seem right. There shouldn't be so many changes associated with this issue and I don't know why the .yaml file would be blank—it isn't blank on GitHub and I can open it in RStudio just fine.  I wonder if you maybe need to pull changes from GitHub or something?

**Comment by jeremylweiss** [comment]
It seems like I fixed whatever was wrong by adapting the process from https://github.com/orgs/community/discussions/36487 to this effort

**Comment by jeremylweiss** [comment]
Restarted the above checklist with a new clone, and `renv::restore()` worked fine. No idea why. But, yay!

However, there are a couple of new issues when I start the .rproj and when I start the app from within RStudio. Any suggestions?

``` r
ℹ Using R 4.3.1 (lockfile was generated with R 4.2.2)
- Project '~/Library/CloudStorage/OneDrive-UniversityofArizona/Documents/azmet/data/new-system/azmet-qa-dashboard' loaded. [renv 1.0.2]
- The project is out-of-sync -- use `renv::status()` for details.
> renv::status()
The following package(s) are out of sync [lockfile -> library]:

# RSPM -----------------------------------------------------------------------
- units   [0.8-2 -> 0.8-3]


See ?renv::status() for advice on resolving these issues.
> renv::snapshot()
The following package(s) will be updated in the lockfile:

# RSPM -----------------------------------------------------------------------
- units   [0.8-2 -> 0.8-3]

The version of R recorded in the lockfile will be updated:
- R       [4.2.2 -> 4.3.1]

Do you want to proceed? [Y/n]: n

- Operation canceled.```

> runApp('app')

Attaching package: ‘arrow’

The following object is masked from ‘package:utils’:

    timestamp

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ lubridate::duration() masks arrow::duration()
✖ dplyr::filter()       masks stats::filter()
✖ dplyr::lag()          masks stats::lag()
ℹ Use the conflicted package to force all conflicts to become errors

Attaching package: ‘data.validator’

The following object is masked from ‘package:shiny’:

    validate

udunits database from /Users/jlweiss/Library/Caches/org.R-project.R/R/renv/cache/v5/R-4.3/aarch64-apple-darwin20/units/0.8-3/422376fe53419adcde4710d43acbcdd0/units/share/udunits/udunits2.xml
Error in `check_auth()` at pins/R/board_connect_server.R:5:2:
! auth = `auto` has failed to find a way to authenticate:
• `server` and `key` not provided for `auth = 'manual'`
• Can't find CONNECT_SERVER and CONNECT_API_KEY envvars for `auth = 'envvar'`
• Can't find any rsconnect::accounts() for `auth = 'rsconnect'`
Run `rlang::last_trace()` to see where the error occurred.
>

**Comment by Aariq** [comment]
This has to do with these lines that read the forecast data from Posit Connect:

https://github.com/uace-azmet/azmet-qa-dashboard/blob/990a4ce3982ea71de6445c696f14e98e05eb3b86/app/app.R#L379-L380

For this to work, you need to authenticate with Posit Connect first.  There are some instructions here: https://pins.rstudio.com/reference/board_connect.html

**Comment by jeremylweiss** [comment]
Ah, yes. I needed to setup the Posit Connect with viz.datascience.arizona.edu on the new mac. Doh.

**Comment by Aariq** [comment]
This is working now, yeah?

**Comment by jeremylweiss** [comment]
I believe so, yes, for both the 'home mac' and the 'office mac'. There is, however, a higher-level issue when I go from one of those machines to the other (which also applies to other cloned repos). Using OneDrive, I get duplicated repos in the file directory and odd commits appearing upon opening the Rproj (below screenshots). I'm looking into what's going on here, but have you ever heard of this before? I've been deleting existing local repos (on OneDrive) and recloning to work around this, but this seems less than optimal.
<img width="537" alt="Screenshot 2023-09-14 at 2 58 46 PM" src="https://github.com/uace-azmet/azmet-qa-dashboard/assets/17934972/076aa560-33cd-49b9-8885-439c6567d04f">
<img width="675" alt="Screenshot 2023-09-14 at 2 40 31 PM" src="https://github.com/uace-azmet/azmet-qa-dashboard/assets/17934972/dc30929d-7fb1-4bf7-9236-59de8a820464">

**Comment by Aariq** [comment]
I don't use OneDrive and haven't seen this particular problem, but git repositories often do not play nicely with shared drives/cloud drives.
